apiVersion: batch/v1
kind: Job
metadata:
  name: hello
spec:
  template:
    # This is the pod template
    spec:
      containers:
      - name: hello
        image: busybox:1.28
        command: ['sh', '-c', 'while true; do date; sleep 2  ; done']
      restartPolicy: OnFailure
    # The pod template ends here
